// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameNftType = "nft_type"

// NftType mapped from table <nft_type>
type NftType struct {
	ID    string  `gorm:"column:id;type:varchar(50);primaryKey" json:"id"` // 唯一标识
	Name  *string `gorm:"column:name;type:varchar(20)" json:"name"`        // 名称
	Value *int64  `gorm:"column:value;type:int" json:"value"`              // 值
}

// TableName NftType's table name
func (*NftType) TableName() string {
	return TableNameNftType
}
