// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTFwlogHistory2019 = "t_fwlog_history_2019"

// TFwlogHistory2019 mapped from table <t_fwlog_history_2019>
type TFwlogHistory2019 struct {
	ID        string     `gorm:"column:id;type:varchar(100);primaryKey" json:"id"`    // ID
	StartDate *time.Time `gorm:"column:startDate;type:datetime" json:"startDate"`     // 访问时间
	StrDate   *string    `gorm:"column:strDate;type:varchar(100)" json:"strDate"`     // 访问时间(毫秒)
	Tomcat    *string    `gorm:"column:tomcat;type:varchar(50)" json:"tomcat"`        // Tomcat
	UserCode  *string    `gorm:"column:userCode;type:varchar(300)" json:"userCode"`   // 登录账号
	UserName  *string    `gorm:"column:userName;type:varchar(200)" json:"userName"`   // 姓名
	SessionID *string    `gorm:"column:sessionId;type:varchar(300)" json:"sessionId"` // sessionId
	IP        *string    `gorm:"column:ip;type:varchar(200)" json:"ip"`               // IP
	FwURL     *string    `gorm:"column:fwUrl;type:varchar(3000)" json:"fwUrl"`        // 访问菜单
	MenuName  *string    `gorm:"column:menuName;type:varchar(100)" json:"menuName"`   // 菜单名称
	Isqx      *string    `gorm:"column:isqx;type:varchar(2)" json:"isqx"`             // 是否有权限访问
	Bak1      *string    `gorm:"column:bak1;type:varchar(100)" json:"bak1"`
	Bak2      *string    `gorm:"column:bak2;type:varchar(100)" json:"bak2"`
	Bak3      *string    `gorm:"column:bak3;type:varchar(100)" json:"bak3"`
	Bak4      *string    `gorm:"column:bak4;type:varchar(100)" json:"bak4"`
	Bak5      *string    `gorm:"column:bak5;type:varchar(100)" json:"bak5"`
}

// TableName TFwlogHistory2019's table name
func (*TFwlogHistory2019) TableName() string {
	return TableNameTFwlogHistory2019
}
