// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTTableindex = "t_tableindex"

// TTableindex mapped from table <t_tableindex>
type TTableindex struct {
	ID       string  `gorm:"column:id;type:varchar(50);primaryKey" json:"id"`             // 表名
	MaxIndex int64   `gorm:"column:maxIndex;type:int;not null;default:1" json:"maxIndex"` // 表记录最大的行,一直累加
	Prefix   string  `gorm:"column:prefix;type:varchar(50);not null" json:"prefix"`       // 前缀 单个字母加 _
	Bak1     *string `gorm:"column:bak1;type:varchar(100)" json:"bak1"`
	Bak2     *string `gorm:"column:bak2;type:varchar(100)" json:"bak2"`
	Bak3     *string `gorm:"column:bak3;type:varchar(100)" json:"bak3"`
	Bak4     *string `gorm:"column:bak4;type:varchar(100)" json:"bak4"`
	Bak5     *string `gorm:"column:bak5;type:varchar(100)" json:"bak5"`
}

// TableName TTableindex's table name
func (*TTableindex) TableName() string {
	return TableNameTTableindex
}
