// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTUserFollow = "t_user_follow"

// TUserFollow mapped from table <t_user_follow>
type TUserFollow struct {
	ID         string    `gorm:"column:id;type:varchar(50);primaryKey" json:"id"`
	UserID     string    `gorm:"column:userId;type:varchar(50);not null" json:"userId"`
	WorksID    string    `gorm:"column:worksId;type:varchar(50);not null" json:"worksId"`
	CreateTime time.Time `gorm:"column:createTime;type:datetime;not null" json:"createTime"`
	UpdateTime time.Time `gorm:"column:updateTime;type:datetime;not null" json:"updateTime"`
	IsValid    *int64    `gorm:"column:isValid;type:int" json:"isValid"` // 用户收藏状态，0表示用户取消收藏，1表示正在收藏
}

// TableName TUserFollow's table name
func (*TUserFollow) TableName() string {
	return TableNameTUserFollow
}
