// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWxMpconfig = "wx_mpconfig"

// WxMpconfig mapped from table <wx_mpconfig>
type WxMpconfig struct {
	ID           string  `gorm:"column:id;type:varchar(50);primaryKey" json:"id"`
	OrgID        string  `gorm:"column:orgId;type:varchar(50);not null" json:"orgId"`       // 站点Id
	AppID        string  `gorm:"column:appId;type:varchar(500);not null" json:"appId"`      // 开发者Id
	Secret       string  `gorm:"column:secret;type:varchar(500);not null" json:"secret"`    // 应用密钥
	Token        *string `gorm:"column:token;type:varchar(500)" json:"token"`               // 开发者令牌
	AesKey       *string `gorm:"column:aesKey;type:varchar(500)" json:"aesKey"`             // 消息加解密密钥
	WxOriginalID *string `gorm:"column:wxOriginalId;type:varchar(500)" json:"wxOriginalId"` // 微信原始ID
	Oauth2       *int64  `gorm:"column:oauth2;type:int;default:1" json:"oauth2"`            // 是否支持微信oauth2.0协议,0是不支持,1是支持
	Active       int64   `gorm:"column:active;type:int;not null;default:1" json:"active"`   // 状态 0不可用,1可用
	Bak1         *string `gorm:"column:bak1;type:varchar(100)" json:"bak1"`
	Bak2         *string `gorm:"column:bak2;type:varchar(100)" json:"bak2"`
	Bak3         *string `gorm:"column:bak3;type:varchar(100)" json:"bak3"`
	Bak4         *string `gorm:"column:bak4;type:varchar(100)" json:"bak4"`
	Bak5         *string `gorm:"column:bak5;type:varchar(100)" json:"bak5"`
}

// TableName WxMpconfig's table name
func (*WxMpconfig) TableName() string {
	return TableNameWxMpconfig
}
