// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAliPayconfig = "ali_payconfig"

// AliPayconfig mapped from table <ali_payconfig>
type AliPayconfig struct {
	ID                   string `gorm:"column:id;type:varchar(50);primaryKey" json:"id"`
	PrivateKey           string `gorm:"column:privateKey;type:varchar(2000)" json:"privateKey"`
	AliPayPublicKey      string `gorm:"column:aliPayPublicKey;type:varchar(1000)" json:"aliPayPublicKey"`
	AppID                string `gorm:"column:appId;type:varchar(50)" json:"appId"`
	ServiceURL           string `gorm:"column:serviceUrl;type:varchar(200);not null" json:"serviceUrl"`
	Charset              string `gorm:"column:charset;type:varchar(20);not null" json:"charset"`
	SignType             string `gorm:"column:signType;type:varchar(10);not null" json:"signType"`
	Format               string `gorm:"column:format;type:varchar(10);not null" json:"format"`
	CertPath             string `gorm:"column:certPath;type:varchar(200)" json:"certPath"`
	AlipayPublicCertPath string `gorm:"column:alipayPublicCertPath;type:varchar(200)" json:"alipayPublicCertPath"`
	RootCertPath         string `gorm:"column:rootCertPath;type:varchar(200)" json:"rootCertPath"`
	EncryptType          string `gorm:"column:encryptType;type:varchar(50)" json:"encryptType"`
	AesKey               string `gorm:"column:aesKey;type:varchar(50)" json:"aesKey"`
}

// TableName AliPayconfig's table name
func (*AliPayconfig) TableName() string {
	return TableNameAliPayconfig
}
