// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGlobalTable = "global_table"

// GlobalTable mapped from table <global_table>
type GlobalTable struct {
	Xid                     string    `gorm:"column:xid;type:varchar(128);primaryKey" json:"xid"`
	TransactionID           int64     `gorm:"column:transaction_id;type:bigint(20)" json:"transaction_id"`
	Status                  int64     `gorm:"column:status;type:tinyint(4);not null" json:"status"`
	ApplicationID           string    `gorm:"column:application_id;type:varchar(32)" json:"application_id"`
	TransactionServiceGroup string    `gorm:"column:transaction_service_group;type:varchar(32)" json:"transaction_service_group"`
	TransactionName         string    `gorm:"column:transaction_name;type:varchar(128)" json:"transaction_name"`
	Timeout                 int64     `gorm:"column:timeout;type:int(11)" json:"timeout"`
	BeginTime               int64     `gorm:"column:begin_time;type:bigint(20)" json:"begin_time"`
	ApplicationData         string    `gorm:"column:application_data;type:varchar(2000)" json:"application_data"`
	GmtCreate               time.Time `gorm:"column:gmt_create;type:datetime;default:null" json:"gmt_create"`
	GmtModified             time.Time `gorm:"column:gmt_modified;type:datetime;default:null" json:"gmt_modified"`
}

// TableName GlobalTable's table name
func (*GlobalTable) TableName() string {
	return TableNameGlobalTable
}
