// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNftCollection = "nft_collection"

// NftCollection mapped from table <nft_collection>
type NftCollection struct {
	ID            string    `gorm:"column:id;type:varchar(50);primaryKey" json:"id"`                // 唯一标识
	UserID        string    `gorm:"column:userId;type:varchar(50);not null" json:"userId"`          // 用户标识
	LogoPath      string    `gorm:"column:logoPath;type:varchar(100);not null" json:"logoPath"`     // logo图地址
	CoverPath     string    `gorm:"column:coverPath;type:varchar(100);not null" json:"coverPath"`   // 合集封面地址
	BannerPath    string    `gorm:"column:bannerPath;type:varchar(100);not null" json:"bannerPath"` // banner图地址
	Name          string    `gorm:"column:name;type:varchar(20);not null" json:"name"`              // 合集名称
	Link          string    `gorm:"column:link;type:varchar(300)" json:"link"`                      // 自定义链接
	Details       string    `gorm:"column:details;type:mediumtext;not null" json:"details"`         // 合集简介
	Type          int64     `gorm:"column:type;type:int(11);not null" json:"type"`                  // 合集类别
	Royalties     string    `gorm:"column:royalties;type:varchar(100);not null" json:"royalties"`   // 合集版税，百分比
	ChainPlatCert string    `gorm:"column:chainPlatCert;type:json" json:"chainPlatCert"`            // 上架后,在不同链平台上链,认证后的数据-json
	IsIn          int64     `gorm:"column:isIn;type:int(11);not null" json:"isIn"`                  // 是否上架 0:否,1:是
	InTime        time.Time `gorm:"column:inTime;type:datetime;default:null" json:"inTime"`         // 上架时间
	OutTime       time.Time `gorm:"column:outTime;type:datetime;default:null" json:"outTime"`       // 下架时间
	IsCert        int64     `gorm:"column:isCert;type:int(11);not null" json:"isCert"`              // 是否平台认证,0:否,1是
	CreateTime    time.Time `gorm:"column:createTime;type:datetime;default:null" json:"createTime"`
	UpdateTime    time.Time `gorm:"column:updateTime;type:datetime;default:null" json:"updateTime"`
	Fire          int64     `gorm:"column:fire;type:int(11)" json:"fire"`                  // 热度值
	SumPrice      float64   `gorm:"column:sumPrice;type:decimal(20,2)" json:"sumPrice"`    // 交易总额
	Lowprice      float64   `gorm:"column:lowprice;type:decimal(20,2)" json:"lowprice"`    // 地板价
	Buyersnum     int64     `gorm:"column:buyersnum;type:int(11)" json:"buyersnum"`        // 拥有者数量
	Weekchange    float64   `gorm:"column:weekchange;type:double(10,2)" json:"weekchange"` // 7天涨跌幅
	Daychange     float64   `gorm:"column:daychange;type:double(10,2)" json:"daychange"`   // 1天涨跌幅
	Symbol        string    `gorm:"column:symbol;type:varchar(20);not null" json:"symbol"` // NFT Symbol
}

// TableName NftCollection's table name
func (*NftCollection) TableName() string {
	return TableNameNftCollection
}
