// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNftWorksPrice = "nft_works_price"

// NftWorksPrice mapped from table <nft_works_price>
type NftWorksPrice struct {
	ID         string    `gorm:"column:id;type:varchar(50);primaryKey" json:"id"`         // 唯一标识
	WorksID    string    `gorm:"column:worksId;type:varchar(50);not null" json:"worksId"` // 作品标识
	DateTime   time.Time `gorm:"column:dateTime;type:datetime;not null" json:"dateTime"`  // 时间
	Price      float64   `gorm:"column:price;type:decimal(20,2);not null" json:"price"`   // 价格
	Ratio      string    `gorm:"column:ratio;type:varchar(6)" json:"ratio"`               // 浮动比例%
	CreateTime time.Time `gorm:"column:createTime;type:datetime;not null" json:"createTime"`
	UpdateTime time.Time `gorm:"column:updateTime;type:datetime;default:null" json:"updateTime"`
	Bak1       string    `gorm:"column:bak1;type:varchar(255)" json:"bak1"`
	Bak2       string    `gorm:"column:bak2;type:varchar(255)" json:"bak2"`
	Bak3       string    `gorm:"column:bak3;type:varchar(255)" json:"bak3"`
}

// TableName NftWorksPrice's table name
func (*NftWorksPrice) TableName() string {
	return TableNameNftWorksPrice
}
