// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNftUserChainplat = "nft_user_chainplat"

// NftUserChainplat mapped from table <nft_user_chainplat>
type NftUserChainplat struct {
	ID            string    `gorm:"column:id;type:varchar(50);primaryKey" json:"id"`                     // 唯一标识
	UserID        string    `gorm:"column:userId;type:varchar(50);not null" json:"userId"`               // 用户标识
	ChainPlatName string    `gorm:"column:chainPlatName;type:varchar(50);not null" json:"chainPlatName"` // 链平台英文名称(标识)
	PrivatePath   string    `gorm:"column:privatePath;type:varchar(200)" json:"privatePath"`             // 私钥地址
	Passwd        string    `gorm:"column:passwd;type:varchar(1000)" json:"passwd"`                      // 密码,使用SecUtils.encoderByRSAPrivateKey()加密后的数据
	PublicPath    string    `gorm:"column:publicPath;type:varchar(200)" json:"publicPath"`               // 公钥地址
	AddressPath   string    `gorm:"column:addressPath;type:varchar(200)" json:"addressPath"`             // ak地址文件路径
	Address       string    `gorm:"column:address;type:varchar(200)" json:"address"`                     // ak地址
	EVMAddress    string    `gorm:"column:EVMAddress;type:varchar(200)" json:"EVMAddress"`               // EVMaddress(由address转换得来的Account.xchainAKToEVMAddress())
	Mnemonic      string    `gorm:"column:mnemonic;type:varchar(100)" json:"mnemonic"`                   // 助记词
	PrevTime      time.Time `gorm:"column:prevTime;type:datetime;default:null" json:"prevTime"`          // 上次链接时间
	CreateTime    time.Time `gorm:"column:createTime;type:datetime;not null" json:"createTime"`
	UpdateTime    time.Time `gorm:"column:updateTime;type:datetime;default:null" json:"updateTime"`
	Bak1          string    `gorm:"column:bak1;type:varchar(255)" json:"bak1"`
	Bak2          string    `gorm:"column:bak2;type:varchar(255)" json:"bak2"`
	Bak3          string    `gorm:"column:bak3;type:varchar(255)" json:"bak3"`
}

// TableName NftUserChainplat's table name
func (*NftUserChainplat) TableName() string {
	return TableNameNftUserChainplat
}
