// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNftChainPlat = "nft_chain_plat"

// NftChainPlat mapped from table <nft_chain_plat>
type NftChainPlat struct {
	ID              string    `gorm:"column:id;type:varchar(50);primaryKey" json:"id"`                        // 唯一标识
	ChainName       string    `gorm:"column:chainName;type:varchar(20);not null" json:"chainName"`            // 链名
	EnglishName     string    `gorm:"column:englishName;type:varchar(20);not null" json:"englishName"`        // 链平台英文名称
	Name            string    `gorm:"column:name;type:varchar(20);not null" json:"name"`                      // 链平台名称
	Details         string    `gorm:"column:details;type:varchar(500);not null" json:"details"`               // 平台描述
	NodeHost        string    `gorm:"column:nodeHost;type:varchar(50);not null" json:"nodeHost"`              // 节点链接地址host=ip+port
	AddressPath     string    `gorm:"column:addressPath;type:varchar(100);not null" json:"addressPath"`       // ak路径(classpath路径下)
	PrivatePath     string    `gorm:"column:privatePath;type:varchar(100);not null" json:"privatePath"`       // 私钥路径(classpath路径下)
	Passwd          string    `gorm:"column:passwd;type:varchar(1000)" json:"passwd"`                         // 密码,使用SecUtils.encoderByRSAPrivateKey()加密后的数据
	PublicPath      string    `gorm:"column:publicPath;type:varchar(100);not null" json:"publicPath"`         // 共钥路径(classpath路径下)非必填
	ContractAccount string    `gorm:"column:contractAccount;type:varchar(50)" json:"contractAccount"`         // 合约账户
	ContractAddress string    `gorm:"column:contractAddress;type:varchar(255)" json:"contractAddress"`        // 合约地址
	BrowserAddress  string    `gorm:"column:browserAddress;type:varchar(255);not null" json:"browserAddress"` // 区块链浏览器地址
	CurrentState    int64     `gorm:"column:currentState;type:int(11);not null" json:"currentState"`          // 当前适配状态 0:适配中,1:适配完成
	Balance         float64   `gorm:"column:balance;type:decimal(20,2);not null" json:"balance,string"`       // root账户余额
	CreateTime      time.Time `gorm:"column:createTime;type:datetime;not null" json:"createTime"`             // 创建时间
	UpdateTime      time.Time `gorm:"column:updateTime;type:datetime;default:null" json:"updateTime"`         // 更新时间
	Bak1            string    `gorm:"column:bak1;type:varchar(255)" json:"bak1"`                              // bak
	Bak2            string    `gorm:"column:bak2;type:varchar(255)" json:"bak2"`
	Bak3            string    `gorm:"column:bak3;type:varchar(255)" json:"bak3"`
}

// TableName NftChainPlat's table name
func (*NftChainPlat) TableName() string {
	return TableNameNftChainPlat
}
