// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTAttachment = "t_attachment"

// TAttachment mapped from table <t_attachment>
type TAttachment struct {
	ID             string    `gorm:"column:id;type:varchar(50);primaryKey" json:"id"`                          // id主键
	OrgID          string    `gorm:"column:orgId;type:varchar(50)" json:"orgId"`                               // 部门id
	OrgTypePathKey string    `gorm:"column:orgTypePathKey;type:varchar(20);default:kjj" json:"orgTypePathKey"` // URL路径中的部门类型,例如 URL路径中的 kjj
	BusinessID     string    `gorm:"column:businessId;type:varchar(50)" json:"businessId"`                     // 业务ID,用于业务关联查询
	AttachmentType int       `gorm:"column:attachmentType;type:int(11)" json:"attachmentType"`                 // 附件类型,1.政策附件.2.企业认证文件3.专家认证文件.4.企业个人认证文件.0.其他文件
	FileName       string    `gorm:"column:fileName;type:varchar(500)" json:"fileName"`                        // 附件名称
	FileURL        string    `gorm:"column:fileURL;type:varchar(2000)" json:"fileURL"`                         // 路径
	Suffix         string    `gorm:"column:suffix;type:varchar(500)" json:"suffix"`                            // 文件后缀
	FileSize       int64     `gorm:"column:fileSize;type:int(11);not null" json:"fileSize"`                    // 文件大小,单位K
	LastDownTime   time.Time `gorm:"column:lastDownTime;type:datetime;default:null" json:"lastDownTime"`       // 最后下载时间
	Sortno         int64     `gorm:"column:sortno;type:int(11);not null" json:"sortno"`                        // 排序,查询时倒叙排列
	Active         int64     `gorm:"column:active;type:int(11);not null;default:1" json:"active"`              // 是否有效(0否,1是)
	CreateUser     string    `gorm:"column:createUser;type:varchar(50);not null" json:"createUser"`            // 创建者
	CreateTime     time.Time `gorm:"column:createTime;type:datetime;not null" json:"createTime"`               // 上传时间
	UpdateUser     string    `gorm:"column:updateUser;type:varchar(50)" json:"updateUser"`                     // 更新者
	UpdateTime     time.Time `gorm:"column:updateTime;type:datetime;default:null" json:"updateTime"`           // 更新时间
	Md5Code        string    `gorm:"column:md5Code;type:varchar(500)" json:"md5Code"`                          // 文件的md5值
}

/*type TAttachment struct {
	ID             string     `gorm:"column:id;type:varchar(50);primaryKey" json:"id"`                          // id主键
	OrgID          string    `gorm:"column:orgId;type:varchar(50)" json:"orgId"`                               // 部门id
	OrgTypePathKey string    `gorm:"column:orgTypePathKey;type:varchar(20);default:kjj" json:"orgTypePathKey"` // URL路径中的部门类型,例如 URL路径中的 kjj
	BusinessID     string    `gorm:"column:businessId;type:varchar(50)" json:"businessId"`                     // 业务ID,用于业务关联查询
	AttachmentType int64     `gorm:"column:attachmentType;type:int(11)" json:"attachmentType"`                 // 附件类型,1.政策附件.2.企业认证文件3.专家认证文件.4.企业个人认证文件.0.其他文件
	FileName       string    `gorm:"column:fileName;type:varchar(500)" json:"fileName"`                        // 附件名称
	FileURL        string    `gorm:"column:fileURL;type:varchar(2000)" json:"fileURL"`                         // 路径
	Suffix         string    `gorm:"column:suffix;type:varchar(500)" json:"suffix"`                            // 文件后缀
	FileSize       int64      `gorm:"column:fileSize;type:int(11);not null" json:"fileSize"`                    // 文件大小,单位K
	LastDownTime   time.Time `gorm:"column:lastDownTime;type:datetime;default:null" json:"lastDownTime"`                    // 最后下载时间
	Sortno         int64      `gorm:"column:sortno;type:int(11);not null" json:"sortno"`                        // 排序,查询时倒叙排列
	Active         int64      `gorm:"column:active;type:int(11);not null;default:1" json:"active"`              // 是否有效(0否,1是)
	CreateUser     string     `gorm:"column:createUser;type:varchar(50);not null" json:"createUser"`            // 创建者
	CreateTime     time.Time  `gorm:"column:createTime;type:datetime;not null" json:"createTime"`               // 上传时间
	UpdateUser     string    `gorm:"column:updateUser;type:varchar(50)" json:"updateUser"`                     // 更新者
	UpdateTime     time.Time `gorm:"column:updateTime;type:datetime;default:null" json:"updateTime"`                         // 更新时间
	Md5Code        string    `gorm:"column:md5Code;type:varchar(500)" json:"md5Code"`                          // 文件的md5值
}*/

// TableName TAttachment's table name
func (*TAttachment) TableName() string {
	return TableNameTAttachment
}
